Crono::CronoJob.create!([
  {job_id: "Perform PublishJob every 1 day at 12:15", log: "I, [2018-02-02T13:13:34.175912 #90994]  INFO -- : Perform PublishJob\nI, [2018-02-02T13:13:34.183308 #90994]  INFO -- : Finished PublishJob in 0.01 seconds\n", last_performed_at: "2018-02-02 06:13:34", healthy: true},
  {job_id: "Perform PublishJob every 1 day at 13:15", log: "I, [2018-02-02T13:15:00.004797 #96823]  INFO -- : Perform PublishJob\nI, [2018-02-02T13:15:00.025172 #96823]  INFO -- : Finished PublishJob in 0.02 seconds\n", last_performed_at: "2018-02-02 06:15:00", healthy: true},
  {job_id: "Perform PublishJob every 1 day at 14:14", log: "I, [2018-02-02T14:14:00.003768 #9920]  INFO -- : Perform PublishJob\nI, [2018-02-02T14:14:00.038378 #9920]  INFO -- : Finished PublishJob in 0.03 seconds\n", last_performed_at: "2018-02-02 07:14:00", healthy: true}
])
Content.create!([
  {title: "Fenty is Launching", author: "Cecilia Dayton", summary: "Nam pretium porttitor e it, quis sollicitudin nulla egestas nec.", content: "Nam pretium porttitor elit, quis sollicitudin nulla egestas nec. Cras vitae ante gravida arcu porttitor molestie a ac justo. Nunc eleifend vel lorem in faucibus. Donec pharetra libero non orci eleifend molestie. Phasellus interdum maximus libero vitae fermentum. Duis id odio sem. Suspendisse sit amet lectus sem. Morbi non sollicitudin erat. Integer sollicitudin molestie quam, tristique rhoncus lacus aliquam quis. Phasellus pharetra auctor odio, non mattis nulla pharetra quis. Etiam sit amet ullamcorper nisl. Donec faucibus vulputate dui at porta.", state: true, published_date: "2018-02-02 07:14:00"},
  {title: "Howtoapplyfoundation", author: "Kurtis Lewis", summary: "Cras in iaculis augue. Aenean quis molestie ante, at rutrum urna.", content: "Cras in iaculis augue. Aenean quis molestie ante, at rutrum urna. Pellentesque fermentum purus nec orci luctus, blandit consectetur est facilisis. Etiam eget est in quam efficitur interdum. Sed pellentesque turpis sit amet velit cursus, ac congue magna condimentum. Cras at purus pharetra lacus maximus aliquet. Vestibulum et metus at orci vehicula pretium tempus eu mi. Vivamus ultrices mi eget ex fermentum interdum. Sed ultrices lectus sed lacus sodales fermentum. Pellentesque rutrum augue id ipsum ullamcorper elementum. Morbi luctus viverra placerat. Donec varius suscipit suscipit. Quisque varius sem non quam egestas rutrum. Nunc eget tristique est. Nam tristique placerat massa, eget molestie velit aliquet id.", state: false, published_date: nil},
  {title: "5Tips to hide eye bags", author: "Cecilia Dayton", summary: "Quisque in urna mauris.", content: "Quisque in urna mauris. Sed fermentum nisi arcu, nec auctor libero pellentesque ut. Cras placerat dui vitae purus euismod malesuada. Pellentesque magna leo, malesuada eu ornare nec, bibendum in tellus. Nam et tincidunt justo. Sed sem lorem, fermentum eget accumsan vel, lobortis vitae nisi. Sed nec euismod eros, ut laoreet erat. Donec convallis sem nec aliquam euismod. In sed nibh pharetra, fringilla quam sit amet, tempor ligula. Duis lacinia eros ac tortor hendrerit ornare. Pellentesque porta urna id nisi sagittis porta.", state: false, published_date: nil}
])
